name: Test
on:
  push:
    branches:
      - "master"
jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up buildx
        uses: docker/setup-buildx-action@v1
      - name: Set up Just
        uses: extractions/setup-just@v1

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - run: 'echo "$FLYTE_CLIENT_SECRET" > client_secret.txt'
        shell: bash
        env:
          FLYTE_CLIENT_SECRET: ${{secrets.FLYTE_CLIENT_SECRET}}
      - name: Save image name
        id: image-name
        run: |
          echo "::set-output name=x::$(just print-full-docker-image-name)"
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.image-name.outputs.x }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Register
        run: |
          just only-register 71
      - name: Test
        run: |
          just test 71
